apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: thegaijin/order
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31536
  selector:
    app: order
