apiVersion: v1
kind: Service
metadata:
  name: order
  labels:
    app: order
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31536
  selector:
    app: order
