apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: thegaijin/demo-apache
          ports:
            - containerPort: 80
