apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    app: customer
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30004
  selector:
    app: customer
