apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: thegaijin/customer
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31491
  selector:
    app: customer
