apiVersion: v1
kind: Service
metadata:
  name: customer
  labels:
    app: customer
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31491
  selector:
    app: customer
