%YAML 1.2
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: thegaijin/catalog
          ports:
            - containerPort: 8080
...
---
apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31818
  selector:
    app: catalog
...
