apiVersion: v1
kind: Service
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30722
  selector:
    app: catalog
