apiVersion: v1
kind: Service
metadata:
  name: apache-service
  labels:
    app: apache
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: NodePort
  selector:
    app: apache
