apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31818
  selector:
    app: apache
